name: reusable workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the artifact
                required: false
                default: dist
                type: string
        outputs:
          result: 
            description: the results of the deployment
            value: ${{ jobs.deploy.outputs.outcome  }}
        #  secrets:
          #  some-secret:
            #  required: false
jobs:
    deploy:
      outputs:
          outcome: ${{ steps.set-result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: list files
              run: ls
            - name: Output information
              run: echo "deploying"
            - name: set result output
              id: set-result
              run: echo "::set-outcome name=step-result::success"